### ISSUE TITLE
How do you split the train/dev/test?

### ISSUE THREAD

**Issue by Stareru** [Zikangli/SOM-NCSCM#1]
Your work and paper is very interesting, but it seems that the splitting of dataset is missing? Do you directly use the 1-3000 as train, 3001-3150 as dev and 3151-3300 as test?

**Comment by Zikangli** [comment]
> Your work and paper is very interesting, but it seems that the splitting of dataset is missing? Do you directly use the 1-3000 as train, 3001-3150 as dev and 3151-3300 as test?

We have uploaded a file to the ./Chinese SC dataset, named shuffled_idx-3300.txt, to show how to get the same train/dev/test data that we used in our paper. :)

**Comment by Stareru** [comment]
Thank you! I will close the issue.
